version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16-browsers
    working_directory: ~/react-memo-game
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: sudo yarn global add @lhci/cli@0.4.x
      - run: lhci autorun